apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: eap62-sample-metrics-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: DeploymentConfig
    name: eap62-sample
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
